### ISSUE TITLE
Torch is flashing on Android Level 14+

### ISSUE THREAD

**Issue by binoculars88** [tjwoon/csZBar#33]
On my Nexus 5 (API Level 22), the flashlight keeps going on and off when option is set to "on".
The quirks mention this behaviour on Android <14, however, this is in my AndroidManifest:

`<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="22" />`

Changing the minSdkVersion to 22 doesn't change this behaviour... I can't get it to stay on. I'm using Ionic Framework.

**Comment by binoculars88** [comment]
Update:
I've noticed that, if I turn the `autoFocusInterval` up to let's say 20000 , the flash turns on, then it turns off for 20 seconds, then it turns on again.

**Comment by binoculars88** [comment]
Update:
I was able to fix this issue changing
        `if(flashMode.equals("on")) {
            camParams.setFlashMode(Camera.Parameters.FLASH_MODE_ON);`

to
        `if(flashMode.equals("on")) {
            camParams.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH);`

Apparently, at least on my Nexus 5, the flash only turn on on focus. Setting it to Torch forces it to stay on. Does anyone have any idea if this workaround I found has consequences (for example: malfunction on other devices or API Levels)?

**Comment by tjwoon** [comment]
Hi @binoculars88 

Yes, this is a known quirk. I am not sure if I did try FLASH_MODE_TORCH previously. If it does work well, that would be good - thank you :+1: 

I think the entire Camera interface will be dropped in favor of Camera2, but I am not sure when or how that will happen.

Will test your fix and apply it to the plugin if no problems are found, but it may take me some time due to workload...
